- name: Install wget
  apt: pkg="wget" state=latest

- name: PostgreSQL | Add repo key
  shell: "wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -"
  warn: false

- name: PostgreSQL | Add repo
  shell: "echo 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' >> /etc/apt/sources.list.d/pgdg.list"
  when: os_version|int == 14.04

- name: PostgreSQL | Add repo
  shell: "echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' >> /etc/apt/sources.list.d/pgdg.list"
  when: os_version|int == 16.04
  warn: false

- name: Update
  become: yes
  shell: "apt-get update"

- name: PostgreSQL | Install
  apt: pkg="postgresql-{{ postgresql_version }}" state=latest update_cache=true

- name: PostgreSQL | Install contrib
  apt: pkg=postgresql-contrib-{{ postgresql_version }} state=latest
  
- name: PostgreSQL | Ensure packages are installed
  action: apt name={{ item }}
  with_items:
    - libpq-dev
    - python-psycopg2

- name: PostgreSQL | Install python-pycurl
  apt: pkg=python-pycurl state=latest

- name: enable service postgresql and ensure it is not masked
  systemd:
    name: postgresql
    enabled: yes
    masked: no
  notify:
    - Restart Postgresql Service