- name: PostgreSQL | Ensure packages are installed
  action: apt name={{ item }}
  with_items:
    - libpq-dev
    - python-psycopg2

- name: PostgreSQL | Install python-pycurl
  apt: pkg=python-pycurl state=latest

- name: PostgreSQL | Add repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc

- name: PostgreSQL | Add repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'

- name: PostgreSQL | Install
  apt: pkg="postgresql-{{ postgresql_version }}" state=latest update_cache=true

- name: PostgreSQL | Install contrib
  apt: pkg=postgresql-contrib-{{ postgresql_version }} state=latest

- name: Systemd | Reload unit configuration
  command: systemctl daemon-reload

- name: Systemd | Activate the launch of the service at boot
  command: systemctl enable postgresql

- name: Systemd | Activate the launch of the service at boot
  command: systemctl enable postgresql

- name: PostgreSQL | Start PostgreSQL
  command: sudo systemctl start postgresql